baseURL = "http://zenoh.io/"
languageCode = "en-us"
title = "zenoh"
theme = "minimal"
disqusShortname = "zenoh" # delete this to disable disqus comments
googleAnalytics = ""
# publishDir = "docs"

[params]
    author = "Angelo Corsaro"
    description = "the __ze__ro __n__etwork __o__ver__h__ead protocol"
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift", "c", "c++", "python"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

[[menu.main]]
  url = "http://zeno.io/download/pdf/2018.04.23-zenoh.pdf"
  name = "Spec"
  weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:angelo.corsaro@adlinktech.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/atolab/Zeno-HE"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/atolab_/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/company/79111/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/"
    name = "stack-overflow"
    weight = 5
